-- Table: public.Partidas

-- DROP TABLE IF EXISTS public."Partidas";

CREATE TABLE IF NOT EXISTS public."Partidas"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Local" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "DataHora" timestamp with time zone NOT NULL,
    "CondicoesClimaticas" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Campeonato" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "TimeCasaId" integer NOT NULL,
    "TimeVisitanteId" integer NOT NULL,
    "PlacarCasa" integer NOT NULL,
    "PlacarVisitante" integer NOT NULL,
    CONSTRAINT "PK_Partidas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Partidas_Times_TimeCasaId" FOREIGN KEY ("TimeCasaId")
        REFERENCES public."Times" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT,
    CONSTRAINT "FK_Partidas_Times_TimeVisitanteId" FOREIGN KEY ("TimeVisitanteId")
        REFERENCES public."Times" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Partidas"
    OWNER to eduardomatuella;
-- Index: IX_Partidas_TimeCasaId

-- DROP INDEX IF EXISTS public."IX_Partidas_TimeCasaId";

CREATE INDEX IF NOT EXISTS "IX_Partidas_TimeCasaId"
    ON public."Partidas" USING btree
    ("TimeCasaId" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: IX_Partidas_TimeVisitanteId

-- DROP INDEX IF EXISTS public."IX_Partidas_TimeVisitanteId";

CREATE INDEX IF NOT EXISTS "IX_Partidas_TimeVisitanteId"
    ON public."Partidas" USING btree
    ("TimeVisitanteId" ASC NULLS LAST)
    TABLESPACE pg_default;


-- Table: public.Jogadores

-- DROP TABLE IF EXISTS public."Jogadores";

CREATE TABLE IF NOT EXISTS public."Jogadores"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Nome" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "ImagemUrl" character varying(200) COLLATE pg_catalog."default",
    "DataNascimento" timestamp with time zone NOT NULL,
    "Altura" double precision NOT NULL,
    "Peso" double precision NOT NULL,
    "Posicao" character varying(30) COLLATE pg_catalog."default" NOT NULL,
    "NumeroCamisa" integer NOT NULL,
    "TimeId" integer NOT NULL,
    "UsuarioId" integer NOT NULL,
    CONSTRAINT "PK_Jogadores" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Jogadores_Times_TimeId" FOREIGN KEY ("TimeId")
        REFERENCES public."Times" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_Jogadores_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId")
        REFERENCES public."Usuarios" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Jogadores"
    OWNER to eduardomatuella;
-- Index: IX_Jogadores_TimeId

-- DROP INDEX IF EXISTS public."IX_Jogadores_TimeId";

CREATE INDEX IF NOT EXISTS "IX_Jogadores_TimeId"
    ON public."Jogadores" USING btree
    ("TimeId" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: IX_Jogadores_UsuarioId

-- DROP INDEX IF EXISTS public."IX_Jogadores_UsuarioId";

CREATE INDEX IF NOT EXISTS "IX_Jogadores_UsuarioId"
    ON public."Jogadores" USING btree
    ("UsuarioId" ASC NULLS LAST)
    TABLESPACE pg_default;


-- Table: public.Partidas

-- DROP TABLE IF EXISTS public."Partidas";

CREATE TABLE IF NOT EXISTS public."Partidas"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Local" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "DataHora" timestamp with time zone NOT NULL,
    "CondicoesClimaticas" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Campeonato" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "TimeCasaId" integer NOT NULL,
    "TimeVisitanteId" integer NOT NULL,
    "PlacarCasa" integer NOT NULL,
    "PlacarVisitante" integer NOT NULL,
    CONSTRAINT "PK_Partidas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Partidas_Times_TimeCasaId" FOREIGN KEY ("TimeCasaId")
        REFERENCES public."Times" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT,
    CONSTRAINT "FK_Partidas_Times_TimeVisitanteId" FOREIGN KEY ("TimeVisitanteId")
        REFERENCES public."Times" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Partidas"
    OWNER to eduardomatuella;
-- Index: IX_Partidas_TimeCasaId

-- DROP INDEX IF EXISTS public."IX_Partidas_TimeCasaId";

CREATE INDEX IF NOT EXISTS "IX_Partidas_TimeCasaId"
    ON public."Partidas" USING btree
    ("TimeCasaId" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: IX_Partidas_TimeVisitanteId

-- DROP INDEX IF EXISTS public."IX_Partidas_TimeVisitanteId";

CREATE INDEX IF NOT EXISTS "IX_Partidas_TimeVisitanteId"
    ON public."Partidas" USING btree
    ("TimeVisitanteId" ASC NULLS LAST)
    TABLESPACE pg_default;



-- Table: public.Times

-- DROP TABLE IF EXISTS public."Times";

CREATE TABLE IF NOT EXISTS public."Times"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Nome" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "CorUniforme" character varying(30) COLLATE pg_catalog."default" NOT NULL,
    "Cidade" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Estado" character varying(2) COLLATE pg_catalog."default" NOT NULL,
    "Fundacao" date NOT NULL,
    "UsuarioId" integer NOT NULL,
    "FotoUrl" character varying(200) COLLATE pg_catalog."default" DEFAULT ''::character varying,
    CONSTRAINT "PK_Times" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Times_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId")
        REFERENCES public."Usuarios" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Times"
    OWNER to eduardomatuella;
-- Index: IX_Times_UsuarioId

-- DROP INDEX IF EXISTS public."IX_Times_UsuarioId";

CREATE INDEX IF NOT EXISTS "IX_Times_UsuarioId"
    ON public."Times" USING btree
    ("UsuarioId" ASC NULLS LAST)
    TABLESPACE pg_default;



-- Table: public.Usuarios

-- DROP TABLE IF EXISTS public."Usuarios";

CREATE TABLE IF NOT EXISTS public."Usuarios"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Nome" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Email" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Senha" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Telefone" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "DataCadastro" timestamp with time zone NOT NULL,
    "UltimoLogin" timestamp with time zone,
    "Ativo" boolean NOT NULL,
    CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Usuarios"
    OWNER to eduardomatuella;